### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by johnwtt** [KadePcGames/Kades-Obfuscater-UTMT-SCRIPT#1]

**Comment by johnwtt** [comment]
(749,10): error CS0246: The type or namespace name 'UndertaleTimline' could not be found (are you missing a using directive or an assembly reference?)

**Comment by Grossley** [comment]
Oh, I see the problem, see it's not supposed to be a "Timline", but a "Timeline".

**Comment by johnwtt** [comment]
(7,22): error CS0234: The type or namespace name 'Forms' does not exist in the namespace 'System.Windows' (are you missing an assembly reference?)

**Comment by Kade-github** [comment]
yeah might fix that.
